### ISSUE TITLE
Build aborts due to errors on Debian.

### ISSUE THREAD

**Issue by lordfeck** [adamsky/globe#20]
Using Debian 10 "Buster" and rustc 1.41.1.

I get the following errors during build:

```
error[E0658]: use of unstable library feature 'matches_macro'
  --> /home/feck/.cargo/registry/src/github.com-1ecc6299db9ec823/crossterm-0.18.2/src/event/filter.rs:16:9
   |
16 |         matches!(*event, InternalEvent::CursorPosition(_, _))
   |         ^^^^^^^
   |
   = note: for more information, see https://github.com/rust-lang/rust/issues/65721

error[E0658]: use of unstable library feature 'matches_macro'
  --> /home/feck/.cargo/registry/src/github.com-1ecc6299db9ec823/crossterm-0.18.2/src/event/filter.rs:26:9
   |
26 |         matches!(*event, InternalEvent::Event(_))
   |         ^^^^^^^
   |
   = note: for more information, see https://github.com/rust-lang/rust/issues/65721

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0658`.
error: could not compile `crossterm`.
warning: build failed, waiting for other jobs to finish...
error: failed to compile `globe-cli v0.1.2`, intermediate artifacts can be found at `/tmp/cargo-install6pFxn7`

Caused by:
  build failed

```

Then the process does not complete.

This may be an issue with an out-of-date rust compiler in the Debian repos, or it may lie elsewhere. Unfortunately my Rust knowledge is non-existent, so I cannot probe any deeper.

**Comment by adamsky** [comment]
>This may be an issue with an out-of-date rust compiler in the Debian repos

Yup, looks like `crossterm` won't work with compiler versions older than `1.42` because of that macro.
